### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by abdel-ships-it** [Scandit/datacapture-cordova-samples#1]
I know you ship typescript definition files in both `scandit-cordova-datacapture-core` and `scandit-cordova-datacapture-barcode` packages. But its not clear how we are supposed to use those. I tried adding them to my `includes` field in the `tsconfig.json` like this

```
"include": [
    "node_modules/scandit-cordova-datacapture-core/**/**.d.ts"
  ]
 ```
 
 But that doesn't work, I still cannot access the `Scandit` namespace. 

I also tried importing them, which works.. but doesn't work at the same time😅
 
 ```typecsript
// throws error File '/node_modules/scandit-cordova-datacapture-core/www/js/index.d.ts' is not a module.ts(2306)
import scanditCore from 'scandit-cordova-datacapture-core'; 
// throws same error  '/node_modules/scandit-cordova-datacapture-core/www/js/index.d.ts' is not a module.ts(2306)
import * as bla from 'scandit-cordova-datacapture-core';
```
I try to access `Scandit` using those imports typescript does return intellisense, which is sadly useless if the imports stop the project from compiling.
 
An example of how we are supposed to use these definitions would be greatly appreciated. Thanks!

**Comment by abdel-ships-it** [comment]
Edit, I have figured it out. Importing like this did the job

```typescript
import 'scandit-cordova-datacapture-core';
import 'scandit-cordova-datacapture-barcode';
```

**Comment by ScanditSupport** [comment]
Hi @realappie 

great that you solved it already. 
In case further questions come up, please fee free to reach out to us via https://support.scandit.com
